version: "3.9"

services:
  template:
    image: node
    container_name: api-template
    hostname: api-template
    networks:
      - infra
    volumes:
      - ./app/:/app
    working_dir: /app
    command: npm run serve
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=infra
      - traefik.http.routers.template.rule=Host(`api.dev.localhost`)
      - traefik.http.routers.template.rule=PathPrefix(`/template/`)
      - traefik.http.routers.template.entrypoints=websecure
      - traefik.http.services.template.loadbalancer.server.port=80

networks:
  infra:
    external: true
